name: Reusable Build and Deploy

on:
  workflow_call:
    inputs:
      build-command:
        required: true
        type: string
      bucket-name:
        required: true
        type: string
      cloudfront-distribution-id:
        required: false
        type: string
        description: "CloudFront distribution ID (optional)"
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:
      - name: Use shared build action
        uses: muskan04yadav/nodejs-build-action@main
        with:
          build-command: ${{ inputs.build-command }}

  deploy:
    name: Deploy to S3
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Use shared deploy action
        uses: muskan04yadav/nodejs-deploy-action@main
        with:
          bucket-name: ${{ inputs.bucket-name }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Invalidate CloudFront Cache
        if: inputs.cloudfront-distribution-id != ''
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ inputs.cloudfront-distribution-id }} \
          --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
